version: '2'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
